#define STB_IMAGE_IMPLEMENTATION

#if _WIN32
	#define STBI_WINDOWS_UTF8
#endif

void dummy_function_to_get_past_gcc_pedantic_because_its_complaining_about_no_real_code_in_this_file_so_ill_give_you_real_code_bro_but_to_be_fair_i_dont_need_to_enable_pedantic_but_like_it_catches_good_errors_like_unused_variables_and_such_so_i_think_this_is_one_of_the_downsides____im_not_going_to_lie_i_thought_this_program_was_gonna_be_simple_and_it_honestly_is_but_like_its_C_so_u_gotta_thug_it_out___i_think_im_adding_too_much_complexity_here_but_hey_learning_experience_or_maybe_its_just_masochistic_behavior_who_knows(void) {}